### PR TITLE
Fixes #10, #9

### LINKED ISSUE #10: Keyboard scroll fires even when element is not focused and hovered by another element
For keyboard scroll to work keydown and mousemove events are bound to the DOM and mouse position is determined with the help of isMouseOver() function, the logic of which is very pure because element may be hovered by some overlay, but it will still be subject to scrolling. I think logic should be like this: we capture mouseover/mouseout events (with jQuery hover() method) on scrollable element and when it is hovered - we start capturing keydown events on document. When element recieves mouseout - we remove keydown listener, because there's no need to capture theese events then. Also, keyboard scroll should be disabled when form elements recieve focus inside scrollable area, because they also use up/down keyboard buttons and container shouldn't be scrolled then. And this functionality should be totally disabled for mobile devices, because they don't have any keyboard anyway :) there's only one way of scrolling - touch.

### PR DESCRIPTION
**Pull request by ekzobrain**
I implemented fixes for mobile zoom in/out and keyboard control problems.

For keyboard controls I implemented two behaviors: the most browser-like (currently active) and hover(), behaving exactly as you plugin previously did, but with honoring form elements (currently commented out).
I think that browser-like approach (element is scrollable with keyboad when it is active/focused) is the best to use, till it provides really native behavior and requires much less code.

### CODE REVIEW

**Comment by mzubala** [comment]
After your changes keyboard scrolling when scrollbars are nested does not work as expected. When I click on nested component and scroll using keyboard also parent container is scrolled. 

Just in case you haven't seen it - demos/nested.html is a test for nested scrollbars. You can observe the wrong behavior in this example.

**Comment by mzubala** [comment]
Your zoom in/out change works well. I pulled it into master. Thanks!

**Comment by mzubala** [comment]
I modified your code a bit to support nested scrollbars. Also when focus was in a text field and you would press up arrow scrolling occurred. I fixed both problems in my last commit to this branch. Pls let me know your thoughts.

**Comment by ekzobrain** [comment]
Yes, seem like keydown event bubbles up the DOM tree and fires on focusable elements. That's not what is said in jQuery docs: "The keydown event is sent to an element when the user first presses a key on the keyboard. It can be attached to any element, but the event is only sent to the element that has the focus" (http://api.jquery.com/keydown/). "Has the focus" and "focusable" are not the same, because only one element can have focus in a moment. So, we should believe to browsers, but not docs :) Your fix is generally correct, but where is a bit better approach: just place event-handler operations into this condition: "if (document.activeElement === _this.$element[0])", "return false" should be removed. It ensures that event is only handled on currently active scrollable element (this excludes form elements and other focusable elements that may cause incorrect behavior (links or user-defined, for example)) and doesn't break event bubbling if user wants to use it somewhere else.

**Pull request merged**
